export const countries = [
  { value: "BR", label: "Brasil" },
  { value: "US", label: "Estados Unidos" },
  { value: "DE", label: "Alemanha" },
  { value: "CH", label: "Suíça" },
  { value: "CN", label: "China" },
  { value: "IN", label: "Índia" },
  { value: "FR", label: "França" },
  { value: "GB", label: "Reino Unido" },
  { value: "IT", label: "Itália" },
  { value: "JP", label: "Japão" },
  { value: "ES", label: "Espanha" },
  { value: "CA", label: "Canadá" },
  { value: "MX", label: "México" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colômbia" },
  { value: "PT", label: "Portugal" },
  { value: "NL", label: "Holanda" },
  { value: "BE", label: "Bélgica" },
  { value: "SE", label: "Suécia" },
  { value: "KR", label: "Coreia do Sul" },
  { value: "AU", label: "Austrália" },
] as const;
